name: Build Flashable Kernel

on:
  workflow_dispatch:

jobs:
  NSK_CI:
    runs-on: ubuntu-22.04
    steps:
      - name: Install packages
         run: |
            sudo apt-get update
            sudo apt-get -y install mkisofs git python2 bc cpio python3 python-is-python3 device-tree-compiler

      - name: Clone Your Kernel Source
        run: |
          cd ~
          git clone --depth=1 https://github.com/frenzy-1112/eleven --recursive kernel

      - name: Setup Clang Toolchain
        run: |
          cd ~
          curl -sL https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r547379.tar.gz > clang.tar.gz
          mkdir clang && tar -xvf clang.tar.gz -C clang
          mkdir -p kernel/clang-llvm
          mv clang/* kernel/clang-llvm/
          rm -rf clang clang.tar.gz

      - name: Build Kernel
        run: |
          cd ~/kernel
          python3 build.py

      - name: Upload Flashable Kernel ZIP
        uses: actions/upload-artifact@v4
        with:
          name: Flashable-Kernel
          path: ~/FlashableKernel.zip
